version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:13.0
    working_directory: ~/working
    steps:
      - checkout
      - attach_workspace:
          at: ~/working
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          keys:
          - maven-{{ checksum "/tmp/maven_cache_seed" }}
          # fallback to latest cache if no exact match found
          - maven-
      - run: mvn clean install --settings '.circleci/settings.xml'
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: cimg/openjdk:13.0
    working_directory: ~/working
    steps:
      - attach_workspace:
          at: ~/working
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          keys:
          - maven-{{ checksum "/tmp/maven_cache_seed" }}
          # fallback to latest cache if no exact match found
          - maven-
      - run:
          name: Deploy to JFrog
          command: mvn deploy --settings '.circleci/settings.xml'
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context:
            - microservicesBuildDev
      - deploy:
          requires:
            - build
          context:
            - microservicesBuildDev
          filters:
            branches:
              only: /^(master|dev)$/
#      - release:
#          requires:
#            - build
#          context:
#            - microservicesBuildDev
#          filters:
#            branches:
#              only: /^release$/

