server:
    port: 8088

# The location of the sample service is provided only for demo purposes.
# For real services, the locations should be dynamically determined (e.g. service discovery).
sample.controller.SampleControllerRest:
    ribbon:
        listOfServers: http://localhost:8080
